permalink: /index.html
include:
  - "_*"
  - ".*"
  - "*.html"
  - "*.js"
  - "*.css"
  - "CNAME"
  
exclude:
  - "node_modules/"
  - ".github/workflows/"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "LICENSE"
