[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https:; font-src 'self' https: data:;"

# Redirect 404 errors to our custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
